services:
  vita:
    container_name: vita
    build: ./Dockerfiles/vita/
    working_dir: /KomodoV2/
    volumes:
      - ./include/vita:/KomodoV2/include/
      - ./src/vita:/KomodoV2/src/
      - ./Makefiles/vita/:/KomodoV2/makefile
      - ./libs/vita:/KomodoV2/libs
      - ./builds/vita:/KomodoV2/build
      - ./assets:/KomodoV2/assets
    command: bash -c "cd /KomodoV2/makefile && make"